services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${localWorkspaceFolderBasename}
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
      - nix:/nix

volumes:
  nix:
     name: nix-store