services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nix-container
    volumes:
      - ..:/workspaces/nix-container:cached
      - nix:/nix

volumes:
  nix:
     name: nix-store