name: "nix-bun-canary-test"

on:
  push:
    branches: [ nix-bun-canary ]
  pull_request:
    branches: [ nix-bun-canary ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Build package
      run: nix build
    
    - name: Check flake
      run: nix flake check
    
    - name: Verify bun-canary execution
      run: |
        result/bin/bun --version
        result/bin/bunx-canary --version