name: "nix-bun-canary-test"

on:
  push:
    branches: [ nix-bun-canary ]
  pull_request:
    branches: [ nix-bun-canary ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Instalation
      run: |
        curl -fsSL https://raw.githubusercontent.com/VV01T3K/nix-container/refs/heads/nix-wsl/install.sh | sh
    
    - name: Build package
      run: . $HOME/.nix-profile/etc/profile.d/nix.sh && nix build
    
    - name: Check flake
      run: . $HOME/.nix-profile/etc/profile.d/nix.sh && nix flake check
    
    - name: Verify bun-canary execution
      run: |
        result/bin/bun --version
        result/bin/bunx-canary --version

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/nix
          /nix/store
        key: ${{ runner.os }}-nix-${{ hashFiles('**/flake.lock') }}