name: "nix-bun-canary-test"

on:
  push:
    branches: [ nix-bun-canary ]
  pull_request:
    branches: [ nix-bun-canary ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Build package
      run: nix build
    
    - name: Check flake
      run: nix flake check
    
    - name: Verify bun-canary execution
      run: |
        result/bin/bun --version
        result/bin/bunx-canary --version

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/nix
          /nix/store
        key: ${{ runner.os }}-nix-${{ hashFiles('**/flake.lock') }}